// flow-typed signature: b20bdd7732b0df09d36c48c42a8cd9d8
// flow-typed version: <<STUB>>/bootstrap-loader_v^2.2.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-loader/extractStyles' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/bootstrap.config' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/bootstrap.loader' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/bootstrap.scripts.loader' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/bootstrap.styles.loader' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/buildExtractStylesLoader' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/checkBootstrapVersion' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/createBootstrapImport' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/createBootstrapRequire' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/createRequire' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/createUserImport' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/fileExists' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/getEnvProp' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/getFontsPath' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/joinLoaders' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/logger' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/processModules' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/processStyleLoaders' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/resolveModule' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/selectModules' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/lib/utils/selectUserModules' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/loader' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/no-op' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/bootstrap.config.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/buildExtractStylesLoader.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/checkBootstrapVersion.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/createBootstrapImport.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/createBootstrapRequire.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/createRequire.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/createUserImport.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/fileExists.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/getEnvProp.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/getFontsPath.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/joinLoaders.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/processModules.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/processStyleLoaders.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/resolveModule.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/selectModules.test' {
  declare module.exports: any;
}

declare module 'bootstrap-loader/node_package/tests/utils/selectUserModules.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-loader/extractStyles.js' {
  declare module.exports: $Exports<'bootstrap-loader/extractStyles'>;
}
declare module 'bootstrap-loader/lib/bootstrap.config.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/bootstrap.config'>;
}
declare module 'bootstrap-loader/lib/bootstrap.loader.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/bootstrap.loader'>;
}
declare module 'bootstrap-loader/lib/bootstrap.scripts.loader.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/bootstrap.scripts.loader'>;
}
declare module 'bootstrap-loader/lib/bootstrap.styles.loader.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/bootstrap.styles.loader'>;
}
declare module 'bootstrap-loader/lib/utils/buildExtractStylesLoader.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/buildExtractStylesLoader'>;
}
declare module 'bootstrap-loader/lib/utils/checkBootstrapVersion.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/checkBootstrapVersion'>;
}
declare module 'bootstrap-loader/lib/utils/createBootstrapImport.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/createBootstrapImport'>;
}
declare module 'bootstrap-loader/lib/utils/createBootstrapRequire.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/createBootstrapRequire'>;
}
declare module 'bootstrap-loader/lib/utils/createRequire.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/createRequire'>;
}
declare module 'bootstrap-loader/lib/utils/createUserImport.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/createUserImport'>;
}
declare module 'bootstrap-loader/lib/utils/fileExists.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/fileExists'>;
}
declare module 'bootstrap-loader/lib/utils/getEnvProp.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/getEnvProp'>;
}
declare module 'bootstrap-loader/lib/utils/getFontsPath.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/getFontsPath'>;
}
declare module 'bootstrap-loader/lib/utils/joinLoaders.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/joinLoaders'>;
}
declare module 'bootstrap-loader/lib/utils/logger.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/logger'>;
}
declare module 'bootstrap-loader/lib/utils/processModules.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/processModules'>;
}
declare module 'bootstrap-loader/lib/utils/processStyleLoaders.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/processStyleLoaders'>;
}
declare module 'bootstrap-loader/lib/utils/resolveModule.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/resolveModule'>;
}
declare module 'bootstrap-loader/lib/utils/selectModules.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/selectModules'>;
}
declare module 'bootstrap-loader/lib/utils/selectUserModules.js' {
  declare module.exports: $Exports<'bootstrap-loader/lib/utils/selectUserModules'>;
}
declare module 'bootstrap-loader/loader.js' {
  declare module.exports: $Exports<'bootstrap-loader/loader'>;
}
declare module 'bootstrap-loader/no-op.js' {
  declare module.exports: $Exports<'bootstrap-loader/no-op'>;
}
declare module 'bootstrap-loader/node_package/tests/bootstrap.config.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/bootstrap.config.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/buildExtractStylesLoader.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/buildExtractStylesLoader.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/checkBootstrapVersion.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/checkBootstrapVersion.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/createBootstrapImport.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/createBootstrapImport.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/createBootstrapRequire.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/createBootstrapRequire.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/createRequire.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/createRequire.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/createUserImport.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/createUserImport.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/fileExists.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/fileExists.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/getEnvProp.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/getEnvProp.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/getFontsPath.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/getFontsPath.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/joinLoaders.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/joinLoaders.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/processModules.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/processModules.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/processStyleLoaders.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/processStyleLoaders.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/resolveModule.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/resolveModule.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/selectModules.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/selectModules.test'>;
}
declare module 'bootstrap-loader/node_package/tests/utils/selectUserModules.test.js' {
  declare module.exports: $Exports<'bootstrap-loader/node_package/tests/utils/selectUserModules.test'>;
}
