// flow-typed signature: 95c5e49367a1854a2516efbcce440e94
// flow-typed version: <<STUB>>/data-driven-motion_v^0.0.11/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'data-driven-motion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'data-driven-motion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'data-driven-motion/dist/data-driven-motion.es' {
  declare module.exports: any;
}

declare module 'data-driven-motion/dist/data-driven-motion' {
  declare module.exports: any;
}

declare module 'data-driven-motion/dist/data-driven-motion.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'data-driven-motion/dist/data-driven-motion.es.js' {
  declare module.exports: $Exports<'data-driven-motion/dist/data-driven-motion.es'>;
}
declare module 'data-driven-motion/dist/data-driven-motion.js' {
  declare module.exports: $Exports<'data-driven-motion/dist/data-driven-motion'>;
}
declare module 'data-driven-motion/dist/data-driven-motion.umd.js' {
  declare module.exports: $Exports<'data-driven-motion/dist/data-driven-motion.umd'>;
}
