// flow-typed signature: b23aa033b574f3df171adf4990b14fb7
// flow-typed version: <<STUB>>/data-driven-motion_v^0.0.9/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'data-driven-motion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'data-driven-motion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'data-driven-motion/es/index' {
  declare module.exports: any;
}

declare module 'data-driven-motion/lib/index' {
  declare module.exports: any;
}

declare module 'data-driven-motion/umd/data-driven-motion' {
  declare module.exports: any;
}

declare module 'data-driven-motion/umd/data-driven-motion.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'data-driven-motion/es/index.js' {
  declare module.exports: $Exports<'data-driven-motion/es/index'>;
}
declare module 'data-driven-motion/lib/index.js' {
  declare module.exports: $Exports<'data-driven-motion/lib/index'>;
}
declare module 'data-driven-motion/umd/data-driven-motion.js' {
  declare module.exports: $Exports<'data-driven-motion/umd/data-driven-motion'>;
}
declare module 'data-driven-motion/umd/data-driven-motion.min.js' {
  declare module.exports: $Exports<'data-driven-motion/umd/data-driven-motion.min'>;
}
