// flow-typed signature: 76ace4501c9d26e23df4c3133ac0d27d
// flow-typed version: <<STUB>>/eslint-plugin-graphql_v^0.6.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-graphql/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-graphql/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-graphql/lib/index'>;
}
