// flow-typed signature: 4bb1b7c8c01e8e6e6988366f72849cf2
// flow-typed version: <<STUB>>/sass-resources-loader_v^1.2.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-resources-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-resources-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass-resources-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'sass-resources-loader/lib/utils/flattenArray' {
  declare module.exports: any;
}

declare module 'sass-resources-loader/lib/utils/isArrayOfStrings' {
  declare module.exports: any;
}

declare module 'sass-resources-loader/lib/utils/logger' {
  declare module.exports: any;
}

declare module 'sass-resources-loader/lib/utils/parseResources' {
  declare module.exports: any;
}

declare module 'sass-resources-loader/lib/utils/processResources' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sass-resources-loader/lib/loader.js' {
  declare module.exports: $Exports<'sass-resources-loader/lib/loader'>;
}
declare module 'sass-resources-loader/lib/utils/flattenArray.js' {
  declare module.exports: $Exports<'sass-resources-loader/lib/utils/flattenArray'>;
}
declare module 'sass-resources-loader/lib/utils/isArrayOfStrings.js' {
  declare module.exports: $Exports<'sass-resources-loader/lib/utils/isArrayOfStrings'>;
}
declare module 'sass-resources-loader/lib/utils/logger.js' {
  declare module.exports: $Exports<'sass-resources-loader/lib/utils/logger'>;
}
declare module 'sass-resources-loader/lib/utils/parseResources.js' {
  declare module.exports: $Exports<'sass-resources-loader/lib/utils/parseResources'>;
}
declare module 'sass-resources-loader/lib/utils/processResources.js' {
  declare module.exports: $Exports<'sass-resources-loader/lib/utils/processResources'>;
}
